services:
    # Nginx Reverse Proxy
    nginx:
        image: nginx:alpine
        container_name: canvora-nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./ssl:/etc/nginx/ssl:ro
            - ./nginx-logs:/var/log/nginx
        depends_on:
            - web
            - ws-server
        networks:
            - canvora-network

    # Next.js Web Application
    web:
        image: whoisasx/canvora-web:latest
        container_name: canvora-web
        restart: unless-stopped
        environment:
            - NODE_ENV=${NODE_ENV}
            - NEXTAUTH_URL=${NEXTAUTH_URL}
            - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
            - AUTH_SECRET=${AUTH_SECRET}
            - DATABASE_URL=${DATABASE_URL}
            - JWT_SECRET=${JWT_SECRET}
            - AUTH_RESEND_KEY=${AUTH_RESEND_KEY}
            - AUTH_GITHUB_ID=${AUTH_GITHUB_ID}
            - AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET}
            - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
            - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
            - BASE_URL=${BASE_URL}
            - WS_URL=${WS_URL}
            - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
            - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
        expose:
            - "3000"
        networks:
            - canvora-network
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
            interval: 30s
            timeout: 10s
            retries: 3

    # WebSocket Server
    ws-server:
        image: whoisasx/canvora-ws:latest
        container_name: canvora-ws-server
        restart: unless-stopped
        environment:
            - NODE_ENV=${NODE_ENV}
            - PORT=8080
            - JWT_SECRET=${JWT_SECRET}
            - BASE_URL=${BASE_URL}
        expose:
            - "8080"
        networks:
            - canvora-network
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
            interval: 30s
            timeout: 10s
            retries: 3

networks:
    canvora-network:
        driver: bridge
