import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeWrapper } from "../components/ThemeWrapper";
import {
	chilanka,
	comic,
	cutive_mono,
	excali,
	firaCode,
	ibm,
	inter,
	jakarta,
	mononoki,
	monospace,
	nunito,
	sourceCode,
	virgil,
} from "./font";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
});

export const metadata: Metadata = {
	title: "Skema",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${jakarta.variable} font-sans`}>
				<ThemeWrapper>{children}</ThemeWrapper>
			</body>
		</html>
	);
}
